### ISSUE TITLE
Advanced Settings Panel

### ISSUE THREAD

**Issue by gilbert** [onaseef/yomobi#133]
Rename "Traffic Booster" panel to "Advanced Settings" and add a [color picker](http://www.eyecon.ro/colorpicker/) for the mobile site header.

**Total time:** `2 hours`

**Comment by onaseef** [comment]
I thought I had documented this in an email, but it may have gotten lost in the mix.  Here's what's supposed to change:
1. Traffic Booster should be renamed to "Advanced Settings"
2. The Mobile Site URL and Desktop Redirect Code fields should be moved to the top of Advanced Settings, with the traffic booster field below it.

3.The Site Name, etc, should now move to the top of General Settings

4.The color picker for the header should appear below the Site Picture field with the label: Set Header Color.

**Comment by onaseef** [comment]
1. Using the color selection changes the color in the mobile emulator, but it didn't change the color in the mobile preview or on the mobile site when I looked at it on my site.
2. Can we change the color picker look to the lighter colored one that we see in the second example <a href=http://www.eyecon.ro/colorpicker>here</a>. Click on the green color picker right below the first black one.
3. When I'm trying to select a color, if I click on a different part of the color box, nothing happens. I actually need to click and drag for something to happen.  Can we make it to where if I single-click somewhere in the color box, it selects that color.
4. I notice you put the updates directly in the main html. Why not create another css sheet called customization.css and insert the header changes there, so that in the future, if we allow additional user customizations, we could put them all in that one location.

Also, the color shouldn't be solid it should be a gradient, created by using the following CSS. So instead of just setting: background=<color>

We'd need to put the following lines in the mobile.css. To be safe, we may still need to use: background: <color> in case there are browsers that don't support gradient

//\* IE10 */ 
background-image: -ms-linear-gradient(top, #ED1D1D 0%, #FFFFFF 275%);

/\* Mozilla Firefox */ 
background-image: -moz-linear-gradient(top, #ED1D1D 0%, #FFFFFF 275%);

/\* Opera */ 
background-image: -o-linear-gradient(top, #ED1D1D 0%, #FFFFFF 275%);

/\* Webkit (Safari/Chrome 10) */ 
background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #ED1D1D), color-stop(2.75, #FFFFFF));

/\* Webkit (Chrome 11+) */ 
background-image: -webkit-linear-gradient(top, #ED1D1D 0%, #FFFFFF 275%);

/\* Proposed W3C Markup */ 
background-image: linear-gradient(top, #ED1D1D 0%, #FFFFFF 275%);

**Comment by gilbert** [comment]
1. Fixed
2. Done
3. It works just like it does the plugin website's examples.
4. They are all in one location. They're in the file `_custom-style.html.erb`

**Comment by onaseef** [comment]
- The most recent set of css changes to the color picker have broken how it works. See <a href="https://docs.google.com/open?id=0B2qHfsz2HClsZWE4MDE3YjktYWJlYi00ZDVjLWI5MDMtMTg5ZWVhNDEzODkx">here.</a>
- The site header color field should now be under General Settings. (See bullet 4 from my comment above from 3rd entry)
- The gradient code wasn't added. See notes under bullet 4 from 4th entry).
- Please make the color picker appear on the same line as the label: Header Color

**Comment by gilbert** [comment]
This all should be taken care of now.
