### ISSUE TITLE
Adding support of multiple sites under one account

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#135]
Add the Site management page that allows users to manage multiple sites from a single account.  What's the time frame we're looking at here?

The navigation on the left would become:

---

General Settings
Advanced Settings
## Site Manager

Edit Mobile Tab Bar

I'll mock up the site manager page.  But I'm thinking it will have a button to create a new site, that takes the user through the wizard again, and list of sites being managed by this user. the user can select one from the list and click "Go to this Site". How much effort is this site management part?

**Comment by gilbert** [comment]
I think the site manager link will be better off in the top right nav bar, since all the links in the left sidebar nav focus on the current site.

Refactoring the backend to allow multiple sites per user will take up to 4 hours. I can't comment on the front end until the mockup is finished.

**Comment by onaseef** [comment]
That's fine.

**Comment by onaseef** [comment]
See UI for Site Manager <a href="https://docs.google.com/open?id=0B2qHfsz2HClsNjBkY2UxYTAtMzM4ZC00NDJiLTgzMGMtMTExZDNlNmE3OWMz">here</a>.

At the top is the url of the current site being managed

You are Managing Site: sgdesignsltd
Site Manager Code (?): [ 34jdiuger]    [Save]     <-- A site manager can set this code to allow other people to manage this site

If the user selects a site in the "Sites You Manage" and clicks:

"Edit Site", we switch to that site
"Stop Managing", confirmation dialog says: "Are you sure you want to stop managing this site", then if Yes, it disappears from the list

NOTE: 
1. There must always be an email address associated with a site so someone can log in.
2. User cannot stop managing their own site, which is the primary site they created
3. We still need to enforce email uniqueness for accounts. 

Add New Site button pops up a dialog where the user types in site name, url, type, email and password & password confirm
NOTE: The primary email for an account needs to be unique, because if the manager stops managing the site, there still needs to be a way for someone to log in to the site

Add Existing Site button pops up dialog where user types in site id: sgdesignsltd and the site manager code.
NOTE: The reason for having a site code instead of using the site's password is because people may use their personal password for their yomobi site and not want to share it with someone who manages their site for them.

**Comment by gilbert** [comment]
Oh ok, so users can also manage _other_ users' sites as well. That makes it a little more involved.

Instead of a Site Manager Code, I suggest a button that generates an access key. Once user A gives this key to user B, the key is assigned to user B and removed from user A's site manager page. User A's site manager will also list user B as a site collaborator, and have a button that revokes user B's access.

Adding an existing site only requires an key. Generated access keys are only valid for the specified site. Emails are already unique.

I also think we need a "default email" field in the general settings panel. This will be the default email that the Leave a Message widget, Call Me Back widget, etc., will use. This new default email will also be populated in the "Add New Site" fields in the site manager.

It will take up to an additional 6 hours to cover the cross-account site collaboration, the site manager page, and the default email general settings field.

**Comment by onaseef** [comment]
The use case scenario is:

Scenario 1: 

I want to build a YoMobi site for someone else and hand it over to them once I've built it, and then be completely done. Since they don't want to give me access to their email password, I need a way to do it that doesn't involve me creating a fake email address just so I can click on the "Validate" link.

Issues:

After an account is created, how do I hand it off to a third party? The only way I can think of is that I give them the email address and password associated with the account.

The requirement is that one email address can be associated with multiple accounts, and multiple email addresses can be associated with one account.  

A site should always have at least one admin so that there is never an orphaned account. The site admin should be able to revoke admin privileges for anyone else on the site, but when it gets down to the last admin, it cannot be revoked

# 

Scenario 2: 

I already have a site, and I want someone to help me with it, so I want to add another person as a collaborator on the site.

Please explain how user A gives user B the key?  Is it by email, or over the phone?  I want to make sure we're on the same page. 

# 

I don't think we need to add a "default email" field to general settings, since there always needs to be an email value associated with a logged in user anyway. We'll use that value by default.

The scenario would be, if I am logged in to YoMobi, and I click "Create New Site", I see a popup with the following required fields:

First Name
Last Name
Email
Site Name
Site URL
Password 1
Password 2

Now, by default, we can populate First Name, Last Name, & Email in that dialog from the values in the admin's primary account. If I logged in to YoMobi as omar@yomobi.com, there is contact information associated with that email. That's the information we'd populate by default into the popup dialog. The user can then change it if they want.

**Comment by gilbert** [comment]
Both scenarios are covered by the generated access key. The key will be securely long enough not to be guessable, and can be given through email, instant message, etc. We can also make it accessible through a url. For example, it might look something like this:

```
www.yomobi.com/site-manager/add-access-key/ff798629617eef9e6f0c8828e383b847961fcae8
```

When the user clicks that link (or pastes the key into the site manager), that user will gain collaborative access to the site associated with that key.

In scenario 1, you would generate an access key like this and give it to the third party. If you want to give them ownership, we'll have to add a button that concedes site ownership privileges.

I think a default email is necessary because - like in your first scenario - if you create a website for someone else, you want widgets like Call Me Back to email that someone else instead of you. Instead of manually changing all the widgets, you can just change that single field in general settings.

**Comment by onaseef** [comment]
Here's how I'd like to do it. Instead of generating an ID, you add users as admins by their site URL. So if someone wants to admin a site, they need to create a personal yomobi account for themselves. Any admin could remove any other admin. If course, there's always an email associated with any account. If one email is associated with numerous accounts, you would log the user into their primary account, which is the account they created themselves with their email address. 

The default email issue is covered by having to enter an email in the new account popup dialog. So when I create an account for someone else, in the new account dialog, I put their email address in the field.  We can default to the admin's email address in the field to make it easier if necessary. 

Does that make sense? Did I miss anything?

**Comment by gilbert** [comment]
Yes, I was assuming that each admin would have their own yomobi account. In your scenario, if user A owns site X, how does he grant access to user B?

I think there still needs to be the concept of a site owner. If I add user C as an admin, I'd like to take comfort that he can't maliciously remove me as an admin.

Yes, the email field in the new account dialog should be the default email. This default email still needs to be an editable field in the general setting panel.

**Comment by onaseef** [comment]
I've created a google doc <a href="https://docs.google.com/document/d/1c9GM_qfjGNM4DOLGEM_I-gvKAWtf5fNyG8O_RSh919I/edit">here</a>.

Please let me know if you have questions about it. It should address the issue of user C malicious removing you as an admin. They only way user C could do that is if he knows the personal password you used to create the site.

I'm still not getting the need for the "default email" field in General Settings. You may be right that we need it, I'm just grasping why, so please help me understand.

The default email for a site is whatever is in the Account Settings field. I guess I don't know how you're doing it on the back end. If the use doesn't input any value in the message widgets, what do you do?  How does the back end work there? Do you leave the widget field empty, and then when you go to the editor for the widget, you populate the email field? And what happens if the user hits "Save" at that point, does you save the email address in the widget itself now, even though it is the "default" email?  And if so, if they later change the "default email", will the value update in the widget?

**Comment by gilbert** [comment]
To recap our phone conversation yesterday:
- Users can create any number of new sites by going to the site manager page, clicking "new site", and going through the site wizard.
  - Whoever creates a site is deemed the site owner.
  - **Note:** I think "company type" and "email associated with site" should be in the first step of the site wizard.
  - We should probably put a soft limit of 10 sites, otherwise malicious users could take over hundreds of urls.
- Site owners can add other yomobi.com account holders as collaborators by adding their primary email address.
  - Site owners can also remove collaborators at any time
  - Site owners may concede site ownership to a collaborator by pressing a button and confirming their password
- Site owners can generate special signup links that are each associated to a site they own
  - When a user signs up through links, they skip the new site wizard and immediately become a collaborator of the site associated with the link.

I think there's still a lot to figure out about the UI. Here's a [very rough updated mockup](https://www.dropbox.com/s/f9fnxrtvddm1c1f/site-manager-1.png).

**Comment by onaseef** [comment]
Here's a <a href="https://docs.google.com/open?id=0B2qHfsz2HClsMGViNjQyMzItN2UyOC00MjkxLTk1YTEtYjc2NGRhOWY0Nzcy">revised mockup.</a>

What questions do you have about the UI. I have a pretty clear vision in my head.

Here are my thoughts:
- When a user creates a new site, they don't need to go through the site wizard. That is only for users who start from the signup screen. I want to minimize the steps involved in creating a new site for admins. The just type in the site name, URL and select the type from the drop-down, and they get the default site. They can click on each widget to fill in the information.
- A soft limit of 10 sites owned is a good idea. Though in the future we'd have a feature that would allow someone to claim a site url that should belong to them, in case someone else took it.

**Comment by gilbert** [comment]
Ok, the wizard skipping sounds good.

Putting the site logo in front of each entry is fine, but it wouldn't make sense to put the logo in front of the user email addresses. I think we should use [gravatar](http://en.gravatar.com/) for that.

In total everything will take up to 12 hours to fully complete.

**Comment by onaseef** [comment]
Since the email is associated with a YoMobi account, it makes sense to use the site logo. I don't really care what  that site logo happens to be.

If the user doesn't have a site logo, we'd use the default ? image we have now.

So in the list, we'd have the site logo on the left with in column 1 with rowspan=2 and the user's first and last name in column 2 row 1, and their email address in column 2, row 2.

**Comment by gilbert** [comment]
I still think it makes more sense to use gravatar. It would be strange for one site's logo to be collaborating with another site's logo. Gravatar is quite popular (github also happens to use them), and is very easy to use. It only requires setting an `<img>` tag's `src` attribute; everything else is managed by gravatar.com.

**Comment by onaseef** [comment]
The goal is to encourage site admins to create a personal YoMobi site.  By linking their collaboration image with their account, we do.

Plus I don't want to create an external dependency.

I imagine if I a person creates a personal site on yomobi, they'll use the same avatar as they use on gravatar or anywhere else.

**Comment by gilbert** [comment]
I thought the main point of the feature was for others to create mobile sites for their clients? Their client's logo would show up as their avatar.

If a user has more than one site, which logo will show up? What about those that signup through a generated signup link?

**Comment by onaseef** [comment]
The goal is for others to create mobile sites for their clients, but hopefully they'd set up a personal yomobi free-lancer account with their logo on it, and use that account to build sites for others.  

When I market it, the instructions will say: Go to YoMobi.com and create a personal freelance account on the site to use as your admin account to build sites for your clients.

The logo that shows up is the one associated with whichever account they designate as their default account.  Even if I'm working on a different site, I always have a default site.

If the account they sign into with the signup link is their only account, then it will start off as their default account. If they later create a personal account, they can designate that personal account as their default account. 

You raised a usability issue.  I can add a collaborator by the email associated with their YoMobi account.  What happens if the collaborator changes their email address on their account?  Will the link be broken?  That's no good. The link between an account and the collaborators needs to be something that is immutable, even if other settings in the account change.

Also, what happens if generate a signup link and mail it to someone who already has a YoMobi account, but I don't know it yet. When they try to sign up, they're going to get an error saying the email is already in use. What happens then?

**Comment by gilbert** [comment]
A user only has a single account, while a user can have multiple sites. "Account" and "user" are synonymous.

Are you saying we're going to have to add additional backend and UI to let users select a default site?

> What happens if the collaborator changes their email address on their account?

The backend only uses the email address to lookup the associated user id.

> what happens if generate a signup link and mail it to someone who already has a YoMobi account

If it says their email is already in use, that should remind them they already have an account. They can then tell the sender that they already have an account, and to add them by email address.

**Comment by onaseef** [comment]
> Are you saying we're going to have to add additional backend and UI to let users select a default site?

Short answer appears to be yes. I had assumed that the site they created when they originally signed up was their default site, but it seems it isn't.

> The backend only uses the email address to lookup the associated user id.

If I add you as a collaborator to a site using the email: gilbert@gmail.com, and then you go into your account and change it to gilbert.garza@gmail.com, doesn't the user account now only have gilbert.garza@gmail.com as the email address? So when the site tries to find you by the original email: gilbert@gmail.com, it won't find you. So we'd have a broken link situation? Or are you saying that when an account is created, it has a unique id that is generated on the back end that remains static even if other account settings change?

> If it says their email is already in use, that should remind them they already have an account. They can then tell the sender that they already have an account, and to add them by email address.

Now I'm thinking we should require everyone to set up a personal account on YoMobi.com.  So instead of me sending you a link and you signing up with it, if I want you to take ownership of your site, I tell you to create a personal site with YoMobi.com, and then tell me the email address you used, and I'll add you as a collaborate that way.  That will drive more people to create YoMobi sites.

**Comment by gilbert** [comment]
>  I had assumed that the site they created when they originally signed up was their default site, but it seems it isn't.

Right now the backend has no concept of "default site", only "site". Once I make it so a user can have more than one site, there needs to be a default site attribute, according to the logo requirements. It's possible that the first site a user creates is their personal site, but it's also possible that it's not. Freelancers, for example, might only care to create sites for others, and sign up with yomobi for the first time creating someone else's site.

> doesn't the user account now only have gilbert.garza@gmail.com as the email address

The backend only uses the email address to lookup the associated user id.  Standard database design is to store and reference a record's id rather than one of its attributes.

> Now I'm thinking we should require everyone to set up a personal account on YoMobi.com.

I don't think that would be pleasant in your Scenario 1 you described. If a client wants to take ownership of his site that someone else built, we shouldn't make him go through the trouble of creating another one that he might not even want.

**Comment by onaseef** [comment]
- NOTE:  When the user signs up with the site key link, we should hide the site type field, since it is already known, and the captcha, since we know it's not a spammer, and make the site key field visible but read only.
- QUESTION: If I have multiple sites, and I click on Account Settings, is the Account Settings information tied to the site I'm editing or is it tied to my User Account?  Is that why you wanted the "default contact information" field?  I assumed that Account Settings was tied to the site, and not the use account, so I just want to clarify
- QUESTION: Can we make the Account Settings button have a down arrow attached to it, so if you click on the link, you're taken to the Account Settings page, and if you click on the arrow, you are show a list of sites you have access to and you can just quick click the site you want to switch to.

**Comment by onaseef** [comment]
Updated Site Manager UI that includes: Make Default button.  See it <a href="https://docs.google.com/open?id=0B2qHfsz2HClsMDQzMTc4ZmItY2ZhZC00NTMyLWExNzgtNjBkNWY3NTYzN2Uy">here</a>.

**Comment by gilbert** [comment]
The default backend and UI will together take 2 hours total.

> is the Account Settings information tied to the site I'm editing or is it tied to my User Account?

The account settings info is tied to your user account.

To answer your second question, yes that's possible. It would take up to an additional two hours to do. I recommend the arrow be next to the site manager button instead of the account settings button.

**Comment by onaseef** [comment]
Yes, I meant for the arrow to be next to the Site Manager page, but we can hold off on that for now. It's not a valuable enough feature right now.

**Comment by gilbert** [comment]
The features are implemented and are ready to be tested. Please open new issues for bugs related to the site manager.
