### ISSUE TITLE
PRODUCTION BUG: WePay iFrame doesn't reappear after hitting cancel

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#436]
Log in to http://www.yomobi.com ymtest@mail.com 123123

Go to the Site Manager, select Site Grade on site "ymtest" and choose to upgrade the site using either payment option. After the WePay iFrame appears, click "Cancel", then repeat the process again.  The second time, the iFrame doesn't appear at all.
You have to refresh the browser for the iFrame to work again.

See: http://ge.tt/9Gd9RgM

**Comment by gilbert** [comment]
Looks like WePay changed their javascript code. To open an iframe, the code YoMobi uses is:

```
WePay.iframe_checkout("checkout_div_id", "checkout_uri");
```

This code is unchanged on our site and [documented on WePay's api page](https://www.wepay.com/developer/tutorial/iframe). However, peering into their source code, they now overwrite the original `iframe_checkout` variable with a DOM element:

``` javascript
function (iframe_container_id, checkout_uri) {
  // ...

  var iframe = document.createElement('iframe');
  iframe.setAttribute('src', checkout_uri);
  iframe.setAttribute('id', 'wepay_checkout_iframe');
  iframe.setAttribute('scrolling', 'no');

  WePay.iframe_checkout = iframe; // <- HERE is the problem

  // ...
}
```

This prevents us from calling the function multiple times, since after the first call, the variable is no longer a function. I can hack a workaround, but I suggest emailing WePay about this. This isn't particularly good practice and probably an oversight on their part.

**Comment by onaseef** [comment]
Thank you for looking into it.  I'll email them. In the mean time, how hacky would a hack be? Could it be that we recreate the iFrame each time?

**Comment by gilbert** [comment]
I would create a reference to the function in another variable and use that variable instead. Fortunately javascript makes it easy to apply a function using a different object for the `this` reference.

**Comment by onaseef** [comment]
That workaround sounds pretty straightforward and not too hacky. Please go ahead and implement it, as I don't know what WePay's response time or response will be.  Thanks

**Comment by onaseef** [comment]
Seems to be a WePay bug that was fixed.
