### ISSUE TITLE
Remove the photo upload feature from above the custom page and category page widgetsD

### ISSUE THREAD

**Issue by onaseef** [onaseef/yomobi#95]
Now that we have image upload directly in pages, we can remove the image upload from above pages. 

We need to add a checkbox to the image upload dialog for pages that says:  "Default Image", with a little ? icon next to it for help. The help text will say:

"The default image for a page appears as a thumbnail next to the page in the category list."  The ? should be a link so if the user clicks on it, the go to help.yomobi.com/<help page for default image> 

If the flag is checked, a thumbnail of that image will appear in front of the page when the page is listed in its category.

If some other image was previously selected as default, we replace it with the new one. If the default image is deleted, we no longer have any thumbnail image.

**Comment by onaseef** [comment]
Duplicate of #94

**Comment by gilbert** [comment]
I'm fine with replacing the photo uploader with something else, but I'll have to charge for the extra time it takes since it wasn't in the original specs.

I think the default checkbox may be a little confusing. Having the thumbnail displayed at the top is much clearer in my opinion. Perhaps a better solution is to have a popup [similar to this](http://www.tinymce.com/js/tinymce/jscripts/tiny_mce/plugins/imagemanager/pages/im/index.html) that allows users to select previously uploaded photos as an alternative to uploading a new one. The popup would be a fixed size somewhat bigger than the mobile site preview popup.

This uploaded photo selector popup would take an hour and a half to complete. It would be accessible on every photo uploader. What do you think?

**Comment by onaseef** [comment]
I'd prefer to keep it as I suggested. Here's my reasoning (though I'm open to feedback):
1. It isn't apparent where the thumbnail photo goes because users only see the photo when the hit the "back" button and go to the category level. 
2. They will probably be using the thumbnail image in their page already, so why make them choose it twice? 
3. There is a small learning curve to the "Default Image" checkbox, but once a user understand its, I think it's clean and intuitive. 
4. The ? button link will help explain the feature. When they do it once, they're golden.
5. It's less work. 

With the checkbox, you don't have to implement a new dialog. You'd add an attribute to the page called: defaultImage, and if a photo is uploaded with the "default image" selected, you just set the value in the page to that image's url. If the value is unchecked or the default image is deleted, you just set the value of defaultImage to null.  

Of course, if the user deletes the image from the page itself with the "delete" button, you'd have to be aware of that and delete the "defaultImage" attribute if necessary.
